# Generated by Django 4.2.7 on 2024-01-14 18:43

from django.db import migrations, models
import django.db.models.deletion
import frauds.models.fraud


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=220)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=220)),
                ("oblast", models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name="Fraud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numEO",
                    models.IntegerField(
                        null=True,
                        validators=[frauds.models.fraud.non_negative_validator],
                    ),
                ),
                ("date", models.CharField(max_length=220)),
                ("victim", models.TextField(blank=True)),
                ("numERDR", models.CharField(blank=True, max_length=15, null=True)),
                ("card_number", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="products",
                        to="frauds.category",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="frauds",
                        to="frauds.district",
                    ),
                ),
            ],
            options={
                "unique_together": {("numEO", "date", "district")},
            },
        ),
    ]
