# Generated by Django 4.2.7 on 2024-01-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frauds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fraud",
            name="date",
            field=models.DateField(),
        ),
    ]
