# Generated by Django 4.2.7 on 2024-01-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frauds", "0003_prison_fraud_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fraud",
            name="phonenumber",
            field=models.FileField(blank=True, null=True, upload_to="num_history/"),
        ),
    ]
