# Generated by Django 4.2.7 on 2024-01-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "frauds",
            "0005_fraud_phonenumber_history_fraud_phonenumber_location_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Imei",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imei", models.CharField(max_length=20)),
                ("num_imei", models.CharField(max_length=20)),
                ("date_up", models.DateField()),
                ("date_to", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Phonenumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=20)),
                ("date_up", models.DateField()),
                ("date_to", models.DateField()),
                (
                    "imei_num",
                    models.ManyToManyField(
                        blank=True, related_name="frauds", to="frauds.imei"
                    ),
                ),
            ],
        ),
    ]
