# Generated by Django 4.2.7 on 2024-01-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frauds", "0006_imei_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imei",
            name="date_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="imei",
            name="date_up",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="date_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="date_up",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="phonenumber",
            name="imei_num",
        ),
        migrations.AddField(
            model_name="phonenumber",
            name="imei_num",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
