# Generated by Django 4.2.7 on 2024-01-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frauds", "0008_phonenumberfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonenumberfile",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
