# Generated by Django 4.2.7 on 2024-02-17 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("frauds", "0009_phonenumberfile_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="fraud",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="frauds",
                to="frauds.category",
            ),
        ),
        migrations.AlterField(
            model_name="phonenumberfile",
            name="data",
            field=models.FileField(upload_to="imei_history/"),
        ),
    ]
