# Generated by Django 4.2.7 on 2024-02-17 14:39

from django.db import migrations, models
import frauds.models.fraud


class Migration(migrations.Migration):
    dependencies = [
        ("frauds", "0010_alter_category_options_alter_fraud_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BSLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=270, null=True)),
                ("LAC", models.CharField(max_length=270)),
                ("SID", models.IntegerField(blank=True, null=True)),
                ("AZ", models.IntegerField(blank=True, null=True)),
                ("lat", models.CharField(blank=True, null=True)),
                ("lon", models.CharField(blank=True, null=True)),
                ("oblast", models.CharField(blank=True, max_length=220, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Control",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.CharField(max_length=220)),
                ("description", models.CharField(max_length=220)),
            ],
        ),
        migrations.AddField(
            model_name="fraud",
            name="damage",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[frauds.models.fraud.non_negative_validator],
            ),
        ),
        migrations.AddField(
            model_name="fraud",
            name="stage_of_crime",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
